### ISSUE TITLE
Supported File Extensions

### ISSUE THREAD

**Issue by JosephTLyons** [atom-ide-community/ide-sourcekit#1]
https://github.com/atom-ide-community/ide-sourcekit/blob/20b01e3bf65f97170a27cfc37d5ee5e1b936b33e/lib/main.js#L18

I'm not sure if SourceKit limits the file extensions to just these or not (I've no idea how these packages work), but there are other formats for C++ language extensions.

C++
`.hh` and `.cc`
`.hpp` and `.cpp`

**Comment by ryanolsonx** [comment]
Oh thanks! I'll add that right away. I included an initial list of extensions I know for the languages sourcekit supports. I can add these ones.
